/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddressDTO from './model/AddressDTO';
import AvailableCategoryDTO from './model/AvailableCategoryDTO';
import BookingDTO from './model/BookingDTO';
import CategoryDTO from './model/CategoryDTO';
import GuestDetailsDTO from './model/GuestDetailsDTO';
import RepresentativeDetailsDTO from './model/RepresentativeDetailsDTO';
import SeasonPriceDTO from './model/SeasonPriceDTO';
import BookingControllerApi from './api/BookingControllerApi';
import CategoryControllerApi from './api/CategoryControllerApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDefinition = require('index'); // See note below*.
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddressDTO model constructor.
     * @property {module:model/AddressDTO}
     */
    AddressDTO,

    /**
     * The AvailableCategoryDTO model constructor.
     * @property {module:model/AvailableCategoryDTO}
     */
    AvailableCategoryDTO,

    /**
     * The BookingDTO model constructor.
     * @property {module:model/BookingDTO}
     */
    BookingDTO,

    /**
     * The CategoryDTO model constructor.
     * @property {module:model/CategoryDTO}
     */
    CategoryDTO,

    /**
     * The GuestDetailsDTO model constructor.
     * @property {module:model/GuestDetailsDTO}
     */
    GuestDetailsDTO,

    /**
     * The RepresentativeDetailsDTO model constructor.
     * @property {module:model/RepresentativeDetailsDTO}
     */
    RepresentativeDetailsDTO,

    /**
     * The SeasonPriceDTO model constructor.
     * @property {module:model/SeasonPriceDTO}
     */
    SeasonPriceDTO,

    /**
    * The BookingControllerApi service constructor.
    * @property {module:api/BookingControllerApi}
    */
    BookingControllerApi,

    /**
    * The CategoryControllerApi service constructor.
    * @property {module:api/CategoryControllerApi}
    */
    CategoryControllerApi
};
