/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.BookingDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BookingDTO', function() {
    it('should create an instance of BookingDTO', function() {
      // uncomment below and update the code to test BookingDTO
      //var instance = new OpenApiDefinition.BookingDTO();
      //expect(instance).to.be.a(OpenApiDefinition.BookingDTO);
    });

    it('should have the property fromDate (base name: "fromDate")', function() {
      // uncomment below and update the code to test the property fromDate
      //var instance = new OpenApiDefinition.BookingDTO();
      //expect(instance).to.be();
    });

    it('should have the property untilDate (base name: "untilDate")', function() {
      // uncomment below and update the code to test the property untilDate
      //var instance = new OpenApiDefinition.BookingDTO();
      //expect(instance).to.be();
    });

    it('should have the property representative (base name: "representative")', function() {
      // uncomment below and update the code to test the property representative
      //var instance = new OpenApiDefinition.BookingDTO();
      //expect(instance).to.be();
    });

    it('should have the property guest (base name: "guest")', function() {
      // uncomment below and update the code to test the property guest
      //var instance = new OpenApiDefinition.BookingDTO();
      //expect(instance).to.be();
    });

  });

}));
