/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GuestDetailsDTO from './GuestDetailsDTO';
import RepresentativeDetailsDTO from './RepresentativeDetailsDTO';

/**
 * The BookingDTO model module.
 * @module model/BookingDTO
 * @version v0
 */
class BookingDTO {
    /**
     * Constructs a new <code>BookingDTO</code>.
     * @alias module:model/BookingDTO
     */
    constructor() { 
        
        BookingDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BookingDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BookingDTO} obj Optional instance to populate.
     * @return {module:model/BookingDTO} The populated <code>BookingDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BookingDTO();

            if (data.hasOwnProperty('fromDate')) {
                obj['fromDate'] = ApiClient.convertToType(data['fromDate'], 'Date');
            }
            if (data.hasOwnProperty('untilDate')) {
                obj['untilDate'] = ApiClient.convertToType(data['untilDate'], 'Date');
            }
            if (data.hasOwnProperty('representative')) {
                obj['representative'] = RepresentativeDetailsDTO.constructFromObject(data['representative']);
            }
            if (data.hasOwnProperty('guest')) {
                obj['guest'] = GuestDetailsDTO.constructFromObject(data['guest']);
            }
        }
        return obj;
    }


}

/**
 * @member {Date} fromDate
 */
BookingDTO.prototype['fromDate'] = undefined;

/**
 * @member {Date} untilDate
 */
BookingDTO.prototype['untilDate'] = undefined;

/**
 * @member {module:model/RepresentativeDetailsDTO} representative
 */
BookingDTO.prototype['representative'] = undefined;

/**
 * @member {module:model/GuestDetailsDTO} guest
 */
BookingDTO.prototype['guest'] = undefined;






export default BookingDTO;

