/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AvailableCategoryDTO model module.
 * @module model/AvailableCategoryDTO
 * @version v0
 */
class AvailableCategoryDTO {
    /**
     * Constructs a new <code>AvailableCategoryDTO</code>.
     * @alias module:model/AvailableCategoryDTO
     */
    constructor() { 
        
        AvailableCategoryDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AvailableCategoryDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AvailableCategoryDTO} obj Optional instance to populate.
     * @return {module:model/AvailableCategoryDTO} The populated <code>AvailableCategoryDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AvailableCategoryDTO();

            if (data.hasOwnProperty('categoryId')) {
                obj['categoryId'] = ApiClient.convertToType(data['categoryId'], 'String');
            }
            if (data.hasOwnProperty('categoryName')) {
                obj['categoryName'] = ApiClient.convertToType(data['categoryName'], 'String');
            }
            if (data.hasOwnProperty('numberAvailable')) {
                obj['numberAvailable'] = ApiClient.convertToType(data['numberAvailable'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} categoryId
 */
AvailableCategoryDTO.prototype['categoryId'] = undefined;

/**
 * @member {String} categoryName
 */
AvailableCategoryDTO.prototype['categoryName'] = undefined;

/**
 * @member {Number} numberAvailable
 */
AvailableCategoryDTO.prototype['numberAvailable'] = undefined;






export default AvailableCategoryDTO;

