/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AvailableCategoryDTO from '../model/AvailableCategoryDTO';
import CategoryDTO from '../model/CategoryDTO';

/**
* CategoryController service.
* @module api/CategoryControllerApi
* @version v0
*/
export default class CategoryControllerApi {

    /**
    * Constructs a new CategoryControllerApi. 
    * @alias module:api/CategoryControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the allCategories operation.
     * @callback module:api/CategoryControllerApi~allCategoriesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CategoryDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/CategoryControllerApi~allCategoriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CategoryDTO>}
     */
    allCategories(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [CategoryDTO];
      return this.apiClient.callApi(
        '/rest/category/all', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the availableCategory operation.
     * @callback module:api/CategoryControllerApi~availableCategoryCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AvailableCategoryDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Date} from 
     * @param {Date} until 
     * @param {module:api/CategoryControllerApi~availableCategoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AvailableCategoryDTO>}
     */
    availableCategory(from, until, callback) {
      let postBody = null;
      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling availableCategory");
      }
      // verify the required parameter 'until' is set
      if (until === undefined || until === null) {
        throw new Error("Missing the required parameter 'until' when calling availableCategory");
      }

      let pathParams = {
      };
      let queryParams = {
        'from': from,
        'until': until
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [AvailableCategoryDTO];
      return this.apiClient.callApi(
        '/rest/category/available', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
