/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AddressDTO from './AddressDTO';

/**
 * The GuestDetailsDTO model module.
 * @module model/GuestDetailsDTO
 * @version v0
 */
class GuestDetailsDTO {
    /**
     * Constructs a new <code>GuestDetailsDTO</code>.
     * @alias module:model/GuestDetailsDTO
     */
    constructor() { 
        
        GuestDetailsDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GuestDetailsDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GuestDetailsDTO} obj Optional instance to populate.
     * @return {module:model/GuestDetailsDTO} The populated <code>GuestDetailsDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GuestDetailsDTO();

            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = AddressDTO.constructFromObject(data['address']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} firstName
 */
GuestDetailsDTO.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
GuestDetailsDTO.prototype['lastName'] = undefined;

/**
 * @member {module:model/AddressDTO} address
 */
GuestDetailsDTO.prototype['address'] = undefined;






export default GuestDetailsDTO;

